name: ESLint Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: npm install

      # ESLint を実行
      - name: Run ESLint
        run: npm run lint
